"""empty message

Revision ID: 337ef85f8bee
Revises: 475c7b56cb65
Create Date: 2017-07-31 20:05:21.138424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337ef85f8bee'
down_revision = '475c7b56cb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
